### ISSUE TITLE
[Question] From decimal to fraction

### ISSUE THREAD

**Issue by Greyberet** [thomasschuerger/rationalj#1]
hi! I've been using rationalJ, and I'm wondering if there's any way to convert a decimal number to a fraction?

**Comment by thomasschuerger** [comment]
There is no built-in method yet. How is the decimal number given? As a String or as a float/double?

If as a String, you can convert "<integerpart>.<fractionalpart>" into "<integerpart><fractionalpart>/1<length-of-fractionalpart-zeroes>" and then use the Rational.of(String) method. For example, "123.456789" would be converted into "123456789/1000000".

**Comment by thomasschuerger** [comment]
Version 1.4.0 has been released. It includes support for providing a decimal number or a decimal number with a repeating fractional part in the `Rational.of(String)` method, using "<integer-part>.<fractional-part>" or "<integer-part>.<fractional-part>_<repeating-fractional-part>". Any or both of <fractional-part> and <repeating-fractional-part> can be empty.

Examples:

- `Rational.of("123.456789")` gives the equivalent of 123456789/1000000
- `Rational.of("1.0_3")` gives the equivalent of 1.033333333... or 31/30
- `Rational.of("123.456_789")` gives the equivalent of 123.456789789789789... or 41111111/333000

**Comment by thomasschuerger** [comment]
Closing the question.
